### ISSUE TITLE
Odd line in testOrbits.py

### ISSUE THREAD

**Issue by danielsf** [lsst/sims_movingObjects#12]
Should line 30 of testOrbits.py be

```
orbits3.readOrbits(os.path.join(self.testdir, 'test_orbitsA.des'))
```
?

If so, there is a problem, because, when I make that change, the `self.assertNotEqual()` line immediately following it fails.  I do not have the expertise to tell whether or not test_orbitsA.des and test_orbitsQ.des are the same orbits but in different format.

**Comment by rhiannonlynne** [comment]
Yes .. and I think this is a difference in py3 vs py2 and None handling. (because it fails in py2 when done correctly). But, it should be all fixed in the PR I'm just giving you :)
