### ISSUE TITLE
Should SEDs be stored in sims_sed_library

### ISSUE THREAD

**Issue by danielsf** [lsst/sims_movingObjects#15]
I see that you added the asteroid SEDs to this repository.  We have been shipping them with sims_sed_library.  Shipping them with sims_sed_library prevents EUPS from downloading a new copy of the SEDs every time the user updates the software repos.  Can we move the SEDs from here to sims_sed_library?

**Comment by rhiannonlynne** [comment]
The asteroid SEDS are so small though -- I didn't want to introduce a dependency on sims_sed_library if I didn't have to (although it may already be a dependency, given that I'm using the camera footprint?).

**Comment by danielsf** [comment]
The camera footprint does not bring in `sims_sed_library`.

`sims_sed_library` is 2.4GB in size.  If you think that is too much to ask people who just care about asteroids to download, then I am fine keeping the asteroid SEDs here.

**Comment by rhiannonlynne** [comment]
I think for now it's reasonable to keep the SEDs here. We can revisit this later if the SEDs grow in number.
