### ISSUE TITLE
unit test produces a suspicious warning

### ISSUE THREAD

**Issue by danielsf** [lsst/sims_movingObjects#17]
The `testRunThrough` method in `testChebyFits.py` produces the following warning

```
testChebyFits.py::TestRun::testRunThrough
  /Users/danielsf/physics/lsst_160212/Development/sims_movingObjects/python/lsst/sims/movingObjects/chebyFits.py:266: UserWarning: Will set length and timestep, but this value of length produces residuals (4493.878602) > skyTolerance (2.500000).
    'produces residuals (%f) > skyTolerance (%f).' % (pos_resid, self.skyTolerance))
```

I'm not sure if this is expected or not, so I thought I would mention it here.

@rhiannonlynne

**Comment by danielsf** [comment]
I did get it when I ran master on my mac, but I am still using python 2.  Let me test with python 3

**Comment by rhiannonlynne** [comment]
Actually, maybe I do. The comment in the code is about "set this here, it's too big, but it will trigger recursion later" ... so I think I should probably catch the warning so that the user doesn't worry about it.

**Comment by rhiannonlynne** [comment]
Ok - so I expect the warning, but I want it to be suppressed so as to not worry others. I have the fix for that.  Where should I put it? on the PR for the pytest/xdist filenames?

**Comment by danielsf** [comment]
Thanks.
