### ISSUE TITLE
orbits.py error for epochs that are not between 16000 - 80000

### ISSUE THREAD

**Issue by brycebolin** [lsst/sims_movingObjects#23]
# Check that the orbit epoch is within a 'reasonable' range, to detect possible column mismatches.
        general_epoch = orbits['epoch'].head(1).values[0]
        expect_min_epoch = 16000.
        expect_max_epoch = 80000.
        if general_epoch < expect_min_epoch or general_epoch > expect_max_epoch:
            raise ValueError("The epoch detected for this orbit is odd - %f. "
                             "Expecting a value between %.1f and %.1f" % (general_epoch,
                                                                          expect_min_epoch,
                                                                          expect_max_epoch))

I recommend removing this part of the code.

**Comment by rhiannonlynne** [comment]
I updated it to allow orbits with epochs between 1800 and 2200.
